fixtures:
  repositories:
    stdlib: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    concat: "git://github.com/puppetlabs/puppetlabs-concat.git"
    file_concat: "git://github.com/electrical/puppet-lib-file_concat.git"
  symlinks:
    dns: "#{source_dir}"
